### PR TITLE
fetch-compose v1.0.1: Fix TypeScript errors for `withRetry`.

### PR DESCRIPTION
**Pull request by mbullington**
# Description

- TypeScript types for `@zeit/fetch-retry` weren't being properly re-exported.

# PR Dependencies

https://github.com/dji-dev/us-web/pull/5

### CODE REVIEW

**Comment by YuanGao0702** [comment]
LGTM

**Comment by joy2king** [comment]
LGTM

**Comment by yanheChen** [comment]
LGTM

**Comment by mbullington** [comment]
If anyone is looking for this I've forked the repo at https://github.com/mbullington/fetch-compose

**Pull request closed without merging**
